In [1]:
from data_collector import get_imf_employment_data, get_imf_gdp_data

imf_raw = get_imf_employment_data()
gdp_raw = get_imf_gdp_data()

In [2]:
countries = list(gdp_raw.COUNTRY.unique())
countries

brazil_gdp = gdp_raw.loc[lambda x: x['COUNTRY'] == 'BRA', ['TIME_PERIOD', 'OBS_VALUE']]
brazil_gdp

    TIME_PERIOD     OBS_VALUE
0       1996-Q1  3.306591e+01
1       1996-Q2  3.389440e+01
2       1996-Q3  3.442331e+01
3       1996-Q4  3.648908e+01
4       1997-Q1  3.632651e+01
..          ...           ...
604     2025-Q1  3.108138e+12
605     2025-Q2  3.174992e+12
606     2025-Q3  3.205998e+12
607     2025-Q4  3.249438e+12
608     2026-Q1  3.339475e+12

[609 rows x 2 columns]

In [ ]:
imf_raw
gdp_raw

,STRUCTURE[;],STRUCTURE_ID,ACTION,COUNTRY,INDICATOR,PRICE_TYPE,S_ADJUSTMENT,TYPE_OF_TRANSFORMATION,FREQUENCY,TIME_PERIOD,...,SERIES_NAME,FULL_DESCRIPTION,KEYWORDS[],KEYWORDS_DATASET[],METHODOLOGY_NOTES,ACCESS_SHARING_NOTES,SHORT_SOURCE_CITATION,FULL_SOURCE_CITATION,LICENSE,SUGGESTED_CITATION
0,dataflow,IMF.STA:QNEA(7.0.0),R,BRA,B1GQ,PD,SA,IX,Q,1996-Q1,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Data are prepared in accordance with the Syste...,NaN,OECD,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
1,dataflow,IMF.STA:QNEA(7.0.0),R,BRA,B1GQ,PD,SA,IX,Q,1996-Q2,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Data are prepared in accordance with the Syste...,NaN,OECD,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
2,dataflow,IMF.STA:QNEA(7.0.0),R,BRA,B1GQ,PD,SA,IX,Q,1996-Q3,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Data are prepared in accordance with the Syste...,NaN,OECD,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
3,dataflow,IMF.STA:QNEA(7.0.0),R,BRA,B1GQ,PD,SA,IX,Q,1996-Q4,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Data are prepared in accordance with the Syste...,NaN,OECD,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
4,dataflow,IMF.STA:QNEA(7.0.0),R,BRA,B1GQ,PD,SA,IX,Q,1997-Q1,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Data are prepared in accordance with the Syste...,NaN,OECD,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,dataflow,IMF.STA:QNEA(7.0.0),R,NaN,B1GQ,Q,SA,USD,NaN,NaN,...,NaN,This dataset provides a snapshot of the econom...,Real GDP,SNA; GDP at current prices;Real GDP,NaN,NaN,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
5106,dataflow,IMF.STA:QNEA(7.0.0),R,HKG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Concepts and definitions are in accordance wit...,NaN,Census and Statistics Department,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
5107,dataflow,IMF.STA:QNEA(7.0.0),R,NaN,B1GQ,V,NSA,USD,NaN,NaN,...,NaN,This dataset provides a snapshot of the econom...,GDP at current prices,SNA; GDP at current prices;Real GDP,NaN,NaN,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
5108,dataflow,IMF.STA:QNEA(7.0.0),R,MAC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,This dataset provides a snapshot of the econom...,NaN,SNA; GDP at current prices;Real GDP,Concepts and definitions are in accordance wit...,NaN,Statistics and Census Service of Macao,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...
5109,dataflow,IMF.STA:QNEA(7.0.0),R,NaN,B1GQ,Q,NSA,USD,NaN,NaN,...,NaN,This dataset provides a snapshot of the econom...,Real GDP,SNA; GDP at current prices;Real GDP,NaN,NaN,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. 2024. National Ec...,International Monetary Fund. National Economic...

In [16]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
country_list = list(gdp_raw.COUNTRY.unique())
country_gdp_dict = {}

for i in country_list:
    
    country_gdp_dict[f'{i}'] = (gdp_raw.loc[lambda x: (x['S_ADJUSTMENT'] == 'SA') & (x['TYPE_OF_TRANSFORMATION'] == 'XDC') & (x['COUNTRY'] == i) & (x['KEYWORDS[]'] == 'Real GDP')]
                                [['COUNTRY','TIME_PERIOD','OBS_VALUE']].assign(DATE = lambda x: pd.to_datetime(x['TIME_PERIOD']),
                                                                               GDP = lambda x: x["OBS_VALUE"])).set_index('DATE').drop(columns = ['TIME_PERIOD', 'OBS_VALUE'])
    

#gdp_filtered = gdp_raw.loc[lambda x: (x['S_ADJUSTMENT'] == 'SA') & (x['TYPE_OF_TRANSFORMATION'] == 'XDC')][['COUNTRY','TIME_PERIOD','OBS_VALUE']]
#gdp_filtered

country_gdp_dict['BRA']

           COUNTRY           GDP
DATE
1996-01-01     BRA  1.754595e+11
1996-04-01     BRA  1.775558e+11
1996-07-01     BRA  1.841067e+11
1996-10-01     BRA  1.823555e+11
1997-01-01     BRA  1.843246e+11
...            ...           ...
2025-01-01     BRA  3.421192e+11
2025-04-01     BRA  3.432817e+11
2025-07-01     BRA  3.436271e+11
2025-10-01     BRA  3.445065e+11
2026-01-01     BRA  3.482971e+11

[121 rows x 2 columns]

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

bra_df = country_gdp_dict['BRA']
usa_df = country_gdp_dict['USA']

fig, ax = plt.subplots(1,2,figsize= (15, 20))
ax[0].set_title('This has to be linear otsebe to forecast (Brazil)')
ax[0].set_ylabel('GDP')
ax[0].set_xlabel("Time, Its quaterly hence why its linear")
sns.lineplot(data= bra_df, x= bra_df.index, y= 'GDP', ax = ax[0] )
ax[1].set_title('This has to be linear otsebe to forecast')
ax[1].set_ylabel('GDP')
ax[1].set_xlabel("Time, Its quaterly hence why its linear (USA)")
sns.lineplot(data= usa_df, x= bra_df.index, y= 'GDP', ax = ax[1] )

plt.show()

KeyError: 'ZAR'