In [ ]:
from data_collector import get_imf_employment_data, get_imf_gdp_data

imf_raw = get_imf_employment_data()
gdp_raw = get_imf_gdp_data()

In [3]:
countries = list(gdp_raw.COUNTRY.unique())
countries

brazil_gdp = gdp_raw.loc[lambda x: x['COUNTRY'] == 'BRA', ['TIME_PERIOD', 'OBS_VALUE']]
brazil_gdp

    TIME_PERIOD     OBS_VALUE
0       1996-Q1  3.306591e+01
1       1996-Q2  3.389440e+01
2       1996-Q3  3.442331e+01
3       1996-Q4  3.648908e+01
4       1997-Q1  3.632651e+01
..          ...           ...
604     2025-Q1  3.108138e+12
605     2025-Q2  3.174992e+12
606     2025-Q3  3.205998e+12
607     2025-Q4  3.249438e+12
608     2026-Q1  3.339475e+12

[609 rows x 2 columns]

In [ ]:
imf_raw
gdp_raw

,STRUCTURE[;],STRUCTURE_ID,ACTION,COUNTRY,INDICATOR,TYPE_OF_TRANSFORMATION,FREQUENCY,TIME_PERIOD,OBS_VALUE,SCALE,...,SERIES_NAME,FULL_DESCRIPTION,KEYWORDS[],KEYWORDS_DATASET[],METHODOLOGY_NOTES,ACCESS_SHARING_NOTES,SHORT_SOURCE_CITATION,FULL_SOURCE_CITATION,LICENSE,SUGGESTED_CITATION
0,dataflow,IMF.STA:LS(9.0.0),R,BRA,U,POP_PCH_PT,Q,1996-Q1,22.535211,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
1,dataflow,IMF.STA:LS(9.0.0),R,BRA,U,POP_PCH_PT,Q,2012-Q3,-4.749460,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
2,dataflow,IMF.STA:LS(9.0.0),R,BRA,U,POP_PCH_PT,Q,2012-Q4,-5.866191,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
3,dataflow,IMF.STA:LS(9.0.0),R,BRA,U,POP_PCH_PT,Q,2013-Q1,11.622390,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
4,dataflow,IMF.STA:LS(9.0.0),R,BRA,U,POP_PCH_PT,Q,2013-Q2,-0.284490,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,dataflow,IMF.STA:LS(9.0.0),R,ZAF,U,YOY_PCH_PT,Q,2024-Q2,2.498147,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
2644,dataflow,IMF.STA:LS(9.0.0),R,ZAF,U,YOY_PCH_PT,Q,2024-Q3,0.401403,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
2645,dataflow,IMF.STA:LS(9.0.0),R,ZAF,U,YOY_PCH_PT,Q,2024-Q4,-0.752543,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
2646,dataflow,IMF.STA:LS(9.0.0),R,ZAF,U,YOY_PCH_PT,Q,2025-Q1,-0.052087,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...
2647,dataflow,IMF.STA:LS(9.0.0),R,ZAF,U,YOY_PCH_PT,Q,2025-Q2,-0.469979,0,...,NaN,Labor Force Statistics provide information on ...,Unemployment rate,Labor force;Employment;Unemployment;Earnings,NaN,NaN,Country authorities,NaN,© International Monetary Fund Copyright. All R...,International Monetary Fund. Labor Force Stati...

In [ ]:
country_list = list(gdp_raw.COUNTRY.unique())
country_gdp_list = []

for i in country_list:
    f'{i}_gdp' = x
    x = gdp_raw.loc[lambda x: (x['S_ADJUSTMENT'] == 'SA') & (x['TYPE_OF_TRANSFORMATION'] == 'XDC') & (x['COUNTRY'] == i)][['COUNTRY','TIME_PERIOD','OBS_VALUE']]
    x.append(country_gdp_list)

#gdp_filtered = gdp_raw.loc[lambda x: (x['S_ADJUSTMENT'] == 'SA') & (x['TYPE_OF_TRANSFORMATION'] == 'XDC')][['COUNTRY','TIME_PERIOD','OBS_VALUE']]
#gdp_filtered

len(country_gdp_list)